name: Update CSV

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *' # Ajoitetaan kerran tunnissa

jobs:
  update-csv:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        pip install pandas

    - name: Update CSV file
      run: |
        python update_csv.py

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add data.csv
        git commit -m 'Update CSV file'
        git push

