name: Update CSV

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/5 * * * *' # Ajoitetaan 5 minuutin välein

jobs:
  update-csv:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        pip install pandas

    - name: Update CSV file
      run: |
        python update_csv.py

    - name: Configure SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        ssh -T git@github.com || exit 255

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git remote set-url origin git@github.com:nikopentik/HYTmap.git
        git add data.csv
        git commit -m 'Update CSV file'
        git push origin main

